-------------------------------------------------------------------------------
Test set: RangersTest
-------------------------------------------------------------------------------
Tests run: 7, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 0.122 sec <<< FAILURE! - in RangersTest
entriesAreDeleted(RangersTest)  Time elapsed: 0.037 sec  <<< ERROR!
org.sql2o.Sql2oException: 
Error in executeUpdate, ERROR: column "phone_number" of relation "rangers" does not exist
  Position: 40
	at RangersTest.entriesAreDeleted(RangersTest.java:67)
Caused by: org.postgresql.util.PSQLException: 
ERROR: column "phone_number" of relation "rangers" does not exist
  Position: 40
	at RangersTest.entriesAreDeleted(RangersTest.java:67)

allSightingsAreReturnedForRanger(RangersTest)  Time elapsed: 0.018 sec  <<< ERROR!
org.sql2o.Sql2oException: 
Error in executeUpdate, ERROR: column "phone_number" of relation "rangers" does not exist
  Position: 40
	at RangersTest.allSightingsAreReturnedForRanger(RangersTest.java:79)
Caused by: org.postgresql.util.PSQLException: 
ERROR: column "phone_number" of relation "rangers" does not exist
  Position: 40
	at RangersTest.allSightingsAreReturnedForRanger(RangersTest.java:79)

findById(RangersTest)  Time elapsed: 0.017 sec  <<< ERROR!
org.sql2o.Sql2oException: 
Error in executeUpdate, ERROR: column "phone_number" of relation "rangers" does not exist
  Position: 40
	at RangersTest.findById(RangersTest.java:40)
Caused by: org.postgresql.util.PSQLException: 
ERROR: column "phone_number" of relation "rangers" does not exist
  Position: 40
	at RangersTest.findById(RangersTest.java:40)

entryIsUpdatedCorrectly(RangersTest)  Time elapsed: 0.013 sec  <<< ERROR!
org.sql2o.Sql2oException: 
Error in executeUpdate, ERROR: column "phone_number" of relation "rangers" does not exist
  Position: 40
	at RangersTest.entryIsUpdatedCorrectly(RangersTest.java:51)
Caused by: org.postgresql.util.PSQLException: 
ERROR: column "phone_number" of relation "rangers" does not exist
  Position: 40
	at RangersTest.entryIsUpdatedCorrectly(RangersTest.java:51)

allEntriesAreSaved(RangersTest)  Time elapsed: 0.012 sec  <<< ERROR!
org.sql2o.Sql2oException: 
Error in executeUpdate, ERROR: column "phone_number" of relation "rangers" does not exist
  Position: 40
	at RangersTest.allEntriesAreSaved(RangersTest.java:20)
Caused by: org.postgresql.util.PSQLException: 
ERROR: column "phone_number" of relation "rangers" does not exist
  Position: 40
	at RangersTest.allEntriesAreSaved(RangersTest.java:20)

